name: PHPUnit Test

on: [push]

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
        laravel: [10.*, 9.*, 8.*]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.*
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 10.*
            php: 7.4
          - laravel: 9.*
            php: 7.4
      fail-fast: false
    name: PHP${{ matrix.php }} - Laravel${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json
          tools: phpunit

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Composer install
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: PHPUnit Testing
        run: vendor/bin/phpunit
